# Generated by Django 4.2.27 on 2026-01-13 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Editora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editora', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=14)),
            ],
            options={
                'verbose_name': 'Editora',
                'db_table': 'Editora',
                'ordering': ['editora'],
            },
        ),
    ]
