# Generated by Django 4.2.27 on 2026-01-16 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Autor',
                'db_table': 'Autor',
                'ordering': ['autor'],
            },
        ),
    ]
