# Generated by Django 4.2.27 on 2026-01-13 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0003_livro_capa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='editora',
        ),
    ]
